spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 596777451508-fhevasc7pshddtmdbi8scg58fvmuhdi0.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
